apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authserver
  template:
    metadata:
      labels:
        app: authserver
    spec:
      containers:
        - name: authserver
          image: egndgd/authserver:latest